const templates = {
    NEW_BOOKING_AVAILABLE: {
        en: { title: 'New job nearby', body: 'A Fixly booking is available in your area.' },
        hi: { title: 'नया काम पास में', body: 'आपके क्षेत्र में एक Fixly बुकिंग उपलब्ध है।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'worker_job',
        channel: 'MULTI',
    },
    BOOKING_ASSIGNED: {
        en: { title: 'New booking assigned', body: 'A customer assigned a service request to you.' },
        hi: { title: 'नई बुकिंग सौंपी गई', body: 'एक ग्राहक ने आपको सेवा अनुरोध सौंपा है।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'worker_job',
        channel: 'MULTI',
    },
    BOOKING_ACCEPTED: {
        en: { title: 'Worker accepted your booking', body: 'Your Fixly worker has accepted the service request.' },
        hi: { title: 'कार्यकर्ता ने बुकिंग स्वीकार की', body: 'आपके Fixly कार्यकर्ता ने सेवा अनुरोध स्वीकार कर लिया है।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    BOOKING_UPDATED: {
        en: { title: 'Booking updated', body: 'Your Fixly booking details have changed.' },
        hi: { title: 'बुकिंग अपडेट हुई', body: 'आपकी Fixly बुकिंग में बदलाव हुआ है।' },
        category: 'BOOKING',
        priority: 'NORMAL',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    BOOKING_CANCELLED: {
        en: { title: 'Booking cancelled', body: 'A Fixly booking was cancelled.' },
        hi: { title: 'बुकिंग रद्द हुई', body: 'एक Fixly बुकिंग रद्द कर दी गई।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    WORKER_ARRIVED: {
        en: { title: 'Worker arrived', body: 'Your Fixly worker has arrived at the location.' },
        hi: { title: 'कार्यकर्ता पहुँच गए', body: 'आपके Fixly कार्यकर्ता स्थान पर पहुँच गए हैं।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_tracking',
        channel: 'MULTI',
    },
    WORKER_ON_THE_WAY: {
        en: { title: 'Worker is on the way', body: 'Your Fixly worker started navigation and is coming to you. Open Track to follow live.' },
        hi: { title: 'कार्यकर्ता रास्ते में हैं', body: 'आपके Fixly कार्यकर्ता ने नेविगेशन शुरू कर दिया है और आपके पास आ रहे हैं। लाइव ट्रैक खोलें।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_tracking',
        channel: 'MULTI',
    },
    JOB_STARTED: {
        en: { title: 'Job started', body: 'Work on your booking has started.' },
        hi: { title: 'काम शुरू हुआ', body: 'आपकी बुकिंग पर काम शुरू हो गया है।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    INVOICE_UPDATED: {
        en: { title: 'Invoice updated', body: 'Parts or charges were added to your booking.' },
        hi: { title: 'इनवॉइस अपडेट हुआ', body: 'आपकी बुकिंग में पार्ट्स या शुल्क जोड़े गए।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'invoice',
        channel: 'MULTI',
    },
    JOB_COMPLETED: {
        en: { title: 'Job completed', body: 'Your Fixly service is complete.' },
        hi: { title: 'काम पूरा हुआ', body: 'आपकी Fixly सेवा पूरी हो गई है।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    PAYMENT_SUCCESS: {
        en: { title: 'Payment successful', body: 'Your Fixly payment was confirmed.' },
        hi: { title: 'भुगतान सफल', body: 'आपका Fixly भुगतान पुष्टि हो गया।' },
        category: 'PAYMENT',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'payment',
        channel: 'MULTI',
    },
    PAYMENT_FAILED: {
        en: { title: 'Payment failed', body: 'We could not confirm your payment. Please try again.' },
        hi: { title: 'भुगतान असफल', body: 'भुगतान की पुष्टि नहीं हो सकी। कृपया फिर कोशिश करें।' },
        category: 'PAYMENT',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'payment',
        channel: 'MULTI',
    },
    PAYMENT_RECEIVED: {
        en: { title: 'Payment received', body: 'Customer payment was confirmed for your job.' },
        hi: { title: 'भुगतान प्राप्त', body: 'आपके काम के लिए ग्राहक भुगतान पुष्टि हो गया।' },
        category: 'PAYMENT',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'wallet',
        channel: 'MULTI',
    },
    WALLET_CREDITED: {
        en: { title: 'Wallet credited', body: 'Earnings were added to your Fixly wallet.' },
        hi: { title: 'वॉलेट में राशि आई', body: 'आपकी कमाई Fixly वॉलेट में जोड़ी गई।' },
        category: 'WALLET',
        priority: 'HIGH',
        entityType: 'wallet',
        action: 'wallet',
        channel: 'MULTI',
    },
    PAYOUT_REQUESTED: {
        en: { title: 'Payout requested', body: 'Your withdrawal request was submitted.' },
        hi: { title: 'पेआउट अनुरोध', body: 'आपका निकासी अनुरोध जमा हो गया।' },
        category: 'PAYOUT',
        priority: 'NORMAL',
        entityType: 'payout',
        action: 'wallet',
        channel: 'MULTI',
    },
    PAYOUT_PROCESSING: {
        en: { title: 'Payout processing', body: 'Your withdrawal is being processed.' },
        hi: { title: 'पेआउट प्रोसेस हो रहा है', body: 'आपकी निकासी प्रोसेस हो रही है।' },
        category: 'PAYOUT',
        priority: 'NORMAL',
        entityType: 'payout',
        action: 'wallet',
        channel: 'MULTI',
    },
    PAYOUT_PAID: {
        en: { title: 'Payout sent', body: 'Your withdrawal was paid.' },
        hi: { title: 'पेआउट भेजा गया', body: 'आपकी निकासी का भुगतान हो गया।' },
        category: 'PAYOUT',
        priority: 'HIGH',
        entityType: 'payout',
        action: 'wallet',
        channel: 'MULTI',
    },
    PAYOUT_REJECTED: {
        en: { title: 'Payout rejected', body: 'Your withdrawal request was rejected.' },
        hi: { title: 'पेआउट अस्वीकृत', body: 'आपका निकासी अनुरोध अस्वीकृत हुआ।' },
        category: 'PAYOUT',
        priority: 'HIGH',
        entityType: 'payout',
        action: 'wallet',
        channel: 'MULTI',
    },
    KYC_APPROVED: {
        en: { title: 'Verification approved', body: 'Your worker verification is approved.' },
        hi: { title: 'सत्यापन स्वीकृत', body: 'आपका कार्यकर्ता सत्यापन स्वीकृत हो गया।' },
        category: 'VERIFICATION',
        priority: 'HIGH',
        entityType: 'verification',
        action: 'verification',
        channel: 'MULTI',
    },
    KYC_REJECTED: {
        en: { title: 'Verification needs attention', body: 'Open verification to see next steps.' },
        hi: { title: 'सत्यापन अधूरा', body: 'अगले कदम देखने के लिए सत्यापन खोलें।' },
        category: 'VERIFICATION',
        priority: 'HIGH',
        entityType: 'verification',
        action: 'verification',
        channel: 'MULTI',
    },
    CERTIFICATE_APPROVED: {
        en: { title: 'Certificate approved', body: 'Your submitted certificate was approved.' },
        hi: { title: 'प्रमाणपत्र स्वीकृत', body: 'आपका प्रमाणपत्र स्वीकृत हो गया।' },
        category: 'VERIFICATION',
        priority: 'NORMAL',
        entityType: 'certificate',
        action: 'verification',
        channel: 'MULTI',
    },
    CERTIFICATE_REJECTED: {
        en: { title: 'Certificate rejected', body: 'Open onboarding to review your certificate.' },
        hi: { title: 'प्रमाणपत्र अस्वीकृत', body: 'प्रमाणपत्र देखने के लिए ऑनबोर्डिंग खोलें।' },
        category: 'VERIFICATION',
        priority: 'HIGH',
        entityType: 'certificate',
        action: 'verification',
        channel: 'MULTI',
    },
    SUPPORT_REPLY: {
        en: { title: 'Support replied', body: 'You have a new reply on your support ticket.' },
        hi: { title: 'सहायता ने जवाब दिया', body: 'आपके सहायता टिकट पर नया जवाब है।' },
        category: 'SUPPORT',
        priority: 'HIGH',
        entityType: 'ticket',
        action: 'support_ticket',
        channel: 'MULTI',
    },
    SUPPORT_STATUS_UPDATED: {
        en: { title: 'Support ticket updated', body: 'Your support ticket status changed.' },
        hi: { title: 'टिकट अपडेट', body: 'आपके सहायता टिकट की स्थिति बदली।' },
        category: 'SUPPORT',
        priority: 'NORMAL',
        entityType: 'ticket',
        action: 'support_ticket',
        channel: 'MULTI',
    },
    SOS_ALERT: {
        en: { title: 'SOS alert', body: 'An emergency SOS was triggered on an active booking.' },
        hi: { title: 'SOS अलर्ट', body: 'सक्रिय बुकिंग पर आपातकालीन SOS भेजा गया।' },
        category: 'SAFETY',
        priority: 'EMERGENCY',
        entityType: 'booking',
        action: 'booking_details',
        channel: 'MULTI',
    },
    EMERGENCY_BOOKING_ALERT: {
        en: { title: 'URGENT: Emergency SOS Job Nearby', body: 'An emergency SOS service request needs immediate attention in your area.' },
        hi: { title: 'अति आवश्यक: आपातकालीन सेवा अनुरोध', body: 'आपके पास तुरंत आपातकालीन सेवा (SOS) का नया अनुरोध आया है।' },
        category: 'SAFETY',
        priority: 'EMERGENCY',
        entityType: 'booking',
        action: 'worker_job',
        channel: 'MULTI',
    },
    SYSTEM_ANNOUNCEMENT: {
        en: { title: 'Fixly announcement', body: 'There is a new platform update.' },
        hi: { title: 'Fixly घोषणा', body: 'प्लेटफ़ॉर्म पर एक नया अपडेट है।' },
        category: 'SYSTEM',
        priority: 'NORMAL',
        entityType: 'system',
        action: 'system',
        channel: 'PUSH',
    },
    MAINTENANCE: {
        en: { title: 'Scheduled maintenance', body: 'Fixly may be briefly unavailable.' },
        hi: { title: 'रखरखाव', body: 'Fixly थोड़े समय के लिए उपलब्ध नहीं हो सकता।' },
        category: 'SYSTEM',
        priority: 'NORMAL',
        entityType: 'system',
        action: 'system',
        channel: 'PUSH',
    },
    PROMOTION: {
        en: { title: 'Fixly offer', body: 'A new Fixly offer is available.' },
        hi: { title: 'Fixly ऑफर', body: 'एक नया Fixly ऑफर उपलब्ध है।' },
        category: 'PROMOTION',
        priority: 'LOW',
        entityType: 'system',
        action: 'system',
        channel: 'PUSH',
    },
    COMPLETION_OTP_SENT: {
        en: { title: 'Job Completion OTP', body: 'Your work is marked done. Please share the completion OTP with the worker if satisfied.' },
        hi: { title: 'कार्य समापन OTP', body: 'कार्य पूरा चिह्नित किया गया है। संतुष्ट होने पर कार्यकर्ता को समापन OTP दें।' },
        category: 'BOOKING',
        priority: 'HIGH',
        entityType: 'booking',
        action: 'open_booking',
        channel: 'PUSH',
    },
};

export const resolveTemplate = (eventType, locale = 'en') => {
    const template = templates[eventType];
    if (!template) {
        return {
            eventType,
            title: 'Fixly Notification',
            body: 'You have a new notification from Fixly.',
            category: 'SYSTEM',
            priority: 'NORMAL',
            entityType: 'system',
            action: 'system',
            channel: 'PUSH',
        };
    }
    const lang = locale?.startsWith('hi') ? 'hi' : 'en';
    return {
        eventType,
        title: template[lang].title,
        body: template[lang].body,
        category: template.category,
        priority: template.priority,
        entityType: template.entityType,
        action: template.action,
        channel: template.channel,
    };
};

export const mapPriorityForStorage = (priority) => {
    const map = {
        LOW: 'Low',
        NORMAL: 'Normal',
        HIGH: 'High',
        URGENT: 'Urgent',
        EMERGENCY: 'Emergency',
        Low: 'Low',
        Normal: 'Normal',
        High: 'High',
        Urgent: 'Urgent',
        Emergency: 'Emergency',
        Medium: 'Normal',
    };
    return map[priority] || 'Normal';
};
